### ISSUE TITLE
Cannot push changes. 

### ISSUE THREAD

**Issue by ortunomarilin** [nays12/QRCode-Authentication-Web#3]

**Comment by nays12** [comment]
Hey just based on some cursory research this might be because you aren't the owner of the repository and need to fork the repository and submit a pull request as opposed to just pushing to the repo. Does visual studio give you this option to fork and submit a pull request?

**Comment by nays12** [comment]
Actually nevermind I think it does!
https://github.com/github/VisualStudio/blob/master/docs/using/creating-a-pull-request.md @ortunomarilin

**Comment by ortunomarilin** [comment]
Ok, I just did it. It allowed me to push my changes and I submitted a pull request.

**Comment by nays12** [comment]
Awesome! I  just approved your request and merged it into the master branch and I guess I'll close this now. Next time you have any issues or questions feel free to post them here and we can hopefully resolve them as quickly as we did this one :) Awesome work girl!

**Comment by nays12** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Web Interface](https://trello.com/c/RLo4dOR7/56-web-interface)
